EduMark/EduMark/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using EduMark.Models;
using Microsoft.AspNetCore.Http;

namespace EduMark.Controllers
{
    public class LoginData
    {
        public string email { get; set; }
        public string password { get; set; }

        public string role { get; set; }

    }

    public class LoginController : Controller
    {
        private readonly ApplicationDbContext _db;

        public LoginController(ApplicationDbContext db)
        {
            _db = db;
        }
        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
        }

        [HttpGet]
        public IActionResult Index()
        {
            var email = HttpContext.Session.GetString("email");
            if (email != null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        #region API Calls
        [HttpPost]
        public async Task<IActionResult> Index(LoginData logindata)
        {
            if (logindata.role == "student" || logindata.role =="teacher")
            {
                var userFromDb = await _db.Users.FirstOrDefaultAsync(u => u.Email == logindata.email && u.Password == logindata.password && u.Role==logindata.role);

                if (userFromDb == null)
                {
                    return Json(new { success = false, message = " Invalid username or password!" });
                }
                
                HttpContext.Session.SetString("email", logindata.email);
                HttpContext.Session.SetString("fullname", userFromDb.FullName);
                HttpContext.Session.SetInt32("userId", userFromDb.Id);
                HttpContext.Session.SetString("role", logindata.role);
                return Json(new { success = true });


            }
            else
            {
                return Json(new { success = false, message = " system error" } );
            }

        }
        #endregion

    }
}

EduMark/EduMark/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EduMark.Models;
using Microsoft.AspNetCore.Mvc;

namespace EduMark.Controllers
{
    public class StudentController : Controller
    {

        private readonly ApplicationDbContext _db;
        public StudentController(ApplicationDbContext db)
        {
            _db = db;
        }
        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

EduMark/EduMark/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using EduMark.Models;



namespace EduMark.Controllers
{
    public class TeacherController : Controller
    {




        private readonly ApplicationDbContext _db;
        public TeacherController(ApplicationDbContext db)
        {
            _db = db;
        }
        protected override void Dispose(bool disposing)
        {
            _db.Dispose();
        }

        public IActionResult Index()
        {
            var email = HttpContext.Session.GetString("email");
            var role = HttpContext.Session.GetString("role");
            if (email == null || role != "teacher")
            {
                return RedirectToAction("Login");
            }
            int teacherId = (int)HttpContext.Session.GetInt32("userId");
            if (teacherId == 0)
            {
                return Json(new { success = false, message = "Login is expired!" });
            }

            var teacher = _db.Users.FirstOrDefaultAsync(u => u.Id == teacherId);
            return View(teacher.Result);          
        }

        public IActionResult Update_Success()
        {
            User user = _db.Users.FirstOrDefault(p => p.Id == HttpContext.Session.GetInt32("userId"));
            return View();
        }


        public IActionResult Main()
        {      
            var email = HttpContext.Session.GetString("email");
            var role = HttpContext.Session.GetString("role");
            if (email == null || role != "teacher")
            {
                return RedirectToAction("Login");
            }
            int teacherId = (int)HttpContext.Session.GetInt32("userId");
            if (teacherId == 0)
            {
                return Json(new { success = false, message = "Login session is expired!" });
            }
            var today = DateTime.Today;

            string[] Days = new string[7];
            string[,] Hours = new string[7, 8];
            for (int i = 1; i < 8; i++)
            {
                var day = today.AddDays(i).ToString("yyyy-MM-dd");
                Days[i - 1] = day;
                for (int j = 9; j < 17; j++)
                {
                    string datetime = day + " " + j + ":00:00";
                    DateTime dt1 = DateTime.Parse(datetime);
                    var available = _db.Availabilities.FirstOrDefaultAsync(u => u.TeacherId == teacherId && u.StartTime == dt1);
                    Availability result = available.Result;
                    Hours[i - 1, j - 9] = (result == null) ? "0" : "1";
                }
            }
            ViewBag.Days = Days;
            ViewBag.Hours = Hours;

            List<Appointment> appts = _db.Appointments.Include(p => p.Student).Include(a => a.Availability).ThenInclude(t => t.Teacher).Where(p => p.Availability.TeacherId == teacherId).ToList();
            ViewBag.Appts = appts;

            var teacher = _db.Users.FirstOrDefaultAsync(u => u.Id == teacherId);
            return View(teacher.Result);
        }

        #region API Calls
        [HttpPost]
        public async Task<IActionResult> SetAvailable(string[][] dayhours, string[] date)
        {
            if (dayhours == null || date == null)
            {
                return Json(new { success = false, message = " Invalid data!" });
            }
            int teacherId = (int)HttpContext.Session.GetInt32("userId");
            if (teacherId == 0)
            {
                return Json(new { success = false, message = "Login session is expired!" });
            }
            for (int i = 0; i < 7; i++)
            {
                string StartDate = date[i];
                for (int j = 9; j < 17; j++)
                {
                    string datetime = StartDate + " " + j + ":00:00";
                    DateTime dt1 = DateTime.Parse(datetime);
                    DateTime dt2 = dt1.AddHours(1);
                    var available = await _db.Availabilities.FirstOrDefaultAsync(u => u.TeacherId == teacherId && u.StartTime == dt1);
                    Availability result = available;
                    if (result == null && dayhours[i][j - 9] == "1")//insert
                    {
                        Availability availability = new Availability();
                        availability.TeacherId = teacherId;
                        availability.StartTime = dt1;
                        availability.EndTime = dt2;
                        _db.Availabilities.Add(availability);
                        _db.SaveChanges();
                    }
                    if (result != null && dayhours[i][j - 9] == "0")//delete
                    {
                        _db.Availabilities.Remove(result);
                        _db.SaveChanges();
                    }
                }
            }

            return Json(new { success = true, message = "Successfully set the availability!" });
        }



        [HttpPost]
        public async Task<IActionResult> UpdateInfo(int teachId, string fullName,string teachLanguages, IFormFile file)
        {
            var updateForm = await _db.Users.FirstOrDefaultAsync(u => u.Id == teachId);
            
            if (updateForm == null)
            {
                return Json(new { success = false, message = " Invalid Teacher!" });
            }

            
            //if (file.Length > 0)
            //{
            //    var fileName = Path.GetRandomFileName();
            //    var path = Path.Combine("~/images/teacher/", fileName);
            //    using (var stream = new FileStream(path, FileMode.Create))
            //    {
            //        await file.CopyToAsync(stream);
            //    }
            //    updateForm.PhotoFile = fileName;
            //}


            
            updateForm.FullName = fullName;
            updateForm.TeachLanguages = teachLanguages;
            _db.Users.Update(updateForm);
            _db.SaveChanges();
            return Json(new { success = true, message = " Update Successfully" });
        }
        #endregion
    }
}

EduMark/EduMark/Views/Login/Index.cshtml
@{
    ViewData["Title"] = "Login";
}
<div id="loginContainer" class="container" style="margin-top:100px;">


    <!-- Form for login-->
    <form id="loginForm" class="mt-3 needs-validation" method="post">

        <!-- Email input -->
        <div class="form-group row align-items-sm-center">
            <label class="d-none d-sm-block col-sm-3 col-form-label"
                   for="email">Email</label>
            <div class="col-12 col-sm-9">
                <input type="text" class="form-control" name="email" id="email" placeholder="Your email" required  value="saperpsh@hotmail.com"/>
            </div>
        </div>
        <!-- End of Email input -->
        <!-- password input -->
        <div class="form-group row align-items-sm-center">
            <label class="d-none d-sm-block col-sm-3 col-form-label"
                   for="password">Password</label>
            <div class="col-12 col-sm-9">
                <input type="password" class="form-control" name="password" id="password" placeholder="Your Password" required value="1q2w3e"/>
            </div>
            <div class="col-6">
                <input type="radio" name="role" value="student" checked />Student
                <input type="radio"  name="role" value="teacher" />Teacher
            
            </div>
        </div>
        <!-- End of password input -->
        <!-- Submit button -->
        <div class="row ">
            <div class="col-12">
                <button type="button" class="btn btn-secondary w-100" id="btnLogin">Sign in</button>
            </div>

    
        </div>
    </form>



</div>

@section Scripts
{
    <script>
        $("#btnLogin").click(function () {
            var roleStatus = $("input[name='role']:checked").val();

            //var urlBaseOnRole = roleStatus == "student" ? "/student" : "/teacher";

            $.ajax({
                url: "/login",
                type: "POST",
                data: {
                    email: $('#email').val(),
                    password: $('#password').val(),
                    role: roleStatus

                },
                success: function (data) {
                    if (data.success) {
                        toastr.success(data.message);
                        var direction = roleStatus == "student" ? '@Url.Action("Index","Student")' : '@Url.Action("Index","Teacher")';
                        $(location).attr('href', direction);
                    }
                    else {
                        toastr.error(data.message);
                    }
                },
                error: function (data) {
                    toastr.error(data.message);
                }
            });
        });
    </script>
}